config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/about',     to: 'static_pages#about'
  
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :index, :show, :create, :destroy]
  resources :microposts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :notifications,       only: :index
  resources :password_resets,     only: [:edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user
  
  def create
    @micropost = Micropost.find(params[:micropost_id]) 
    @comment = @micropost.comments.build(comment_params) 
    @comment.user_id = current_user.id 
    if @comment.save
      @micropost.create_notification_comment!(current_user, @comment.id)
      render :index 
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) 
    if @comment.destroy
      render :index 
    end
  end

  private
  
    def comment_params
      params.require(:comment).permit(:content, :micropost_id, :user_id)
    end
    
end

app/views/comments/_form.html.erb
<%= form_with(model: [micropost, comment] ) do |form| %> 
  <div>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<%  if comments.present? %> 
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <p><%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %></p>
      <p>コメント：<%= comment.content %></p>
      <% if comment.user == current_user %>
       <p><%= link_to 'コメントを削除する',micropost_comment_path(comment.micropost_id, comment.id), method: :delete, remote: true %></p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.micropost.comments }) %>")
$("textarea").val('')