config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/about',     to: 'static_pages#about'
  
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :index, :show, :create, :destroy]
  resources :microposts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :notifications,       only: :index
  resources :password_resets,     only: [:edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
  </span>
  <div class="field">
    <%= f.text_area :content, placeholder: "Comments on images" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search_form.html.erb
<%= form_tag(microposts_path,:method => 'get') do  %>
<%= text_field_tag :search ,"",{placeholder: "検索"}  %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a  class="no_link">
    <strong class="stat">
     <%= @user.microposts.count %>
    </strong>
    投稿数
  </a>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
  <br>
</div>
<div>
  <br>
  <%= @user.introduce %>
  <br>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>