config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/about',     to: 'static_pages#about'
  
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:new, :index, :show, :create, :destroy]
  resources :microposts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
  resources :notifications,       only: :index
  resources :password_resets,     only: [:edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if logged_in? %>
    <%= link_to new_micropost_path do%>
    <i class="fab fa-instagram" aria-hidden="true" style="font-size: 1.5em;"></i>
    <% end %>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "insta app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="search"><%= render 'shared/search_form' %></li>
        <% if logged_in? %>
          <li>
            <%= link_to  users_path do%>
              <i class="fa fa-users" aria-hidden="true" style="font-size: 1.5em;"></i>
            <% end %>
          </li>
          <li>
            <%= link_to  notifications_path do %>
              <% if unchecked_notifications.any? %>
                <span class="fa-stack">
                  <i class="far fa-bell fa-lg fa-stack-2x" aria-hidden="true" style="font-size: 1.5em;"></i> 
                  <i class="fas fa-circle n-circle fa-stack-1x" aria-hidden="true"></i>
                </span>
              <% else %>
                <i class="far fa-bell fa-lg" aria-hidden="true"  style="font-size: 1.5em;"></i> 
              <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to  current_user do %>
              <i class="fa fa-user-circle" aria-hidden="true" style="font-size: 1.5em;"></i>
            <% end %>
          </li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
       <%= yield %>
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>